#!/bin/bash

IMAGE_NAME=konnected-2-1
PORT=/dev/cu.wchusbserial1420

esptool.py --port=${PORT} write_flash --flash_mode dio 0x00000 firmware/${IMAGE_NAME}.bin

cd src

while true; do
  sleep 2
  nodemcu-uploader --port=${PORT} upload * --verify=raw && break
done

nodemcu-uploader --port=${PORT} node restart

tput bel