#!/bin/bash

PORT=/dev/cu.SLAB_USBtoUART
FIRMWARE_PATH="${PWD}/../nodemcu-firmware"
BUILD_PATH="firmware/builds/dev"

# Build LFS image with application files
docker run -e "IMAGE_NAME=lfs" \
    --rm -ti -v "${FIRMWARE_PATH}:/opt/nodemcu-firmware" \
    -v "${PWD}/src/lfs:/opt/lua" marcelstoer/nodemcu-build lfs-image

mv src/lfs/LFS_integer_lfs.img src/lfs/lfs.img
rm -f src/lfs/LFS_float_lfs.img

# Build SPIFFS image
docker run \
    --rm -ti -v "${FIRMWARE_PATH}:/opt/nodemcu-firmware" \
    -v "${PWD}/scripts:/scripts" \
    -v "${PWD}/src:/opt/lua" marcelstoer/nodemcu-build bash /scripts/build-spiffs

mkdir -p "${BUILD_PATH}"
rm -rf "${BUILD_PATH}/*"

cp "${FIRMWARE_PATH}/bin/konnected-filesystem-0x100000.img" "${BUILD_PATH}/konnected-filesystem-0x100000-dev.img"

esptool.py "--port=${PORT}" write_flash --flash_mode dio 0x100000 "${BUILD_PATH}/konnected-filesystem-0x100000-dev.img"